######################################################################
# Automatically generated by qmake (3.0) Wed Dec 16 10:34:43 2015
######################################################################

QT += widgets
TEMPLATE = app
TARGET = UCAS_supplicant
INCLUDEPATH += . include

# Input
HEADERS += include/connect.h include/qt_extended.hh
SOURCES += src/Connect.cc \
           src/ProcessResult.cc \
           src/qt_main.cc \
           src/qt_supplementary.cc
